import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider } from "@/providers/toast-provider";
import { WagmiProviders } from "@/providers/wagmi";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="font-aileron antialiased">
        <WagmiProviders>
          <ToastProvider>
            {children}
          </ToastProvider>
        </WagmiProviders>
      </body>
    </html>
  );
}
